apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "pradeepgadde.com"
  - ip: "192.168.1.1"
    hostnames:
    - "kubernetes.io"
  containers:
  - command:
    - cat
    - /etc/hosts
    image: busybox
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
